---
- name: Update and Upgrade all repos and packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    force_apt_get: yes
- name: Install Python3 and Pip3
  apt:
    update_cache: yes
    pkg:
      - python
      - python-pip
      - python-dev
      - python3
      - python3-pip
      - python3-dev
- name: Install Git and Curl
  apt:
    update_cache: yes
    pkg:
      - git
      - curl